#import "../preamble.typ": *

= Introduction <introduction>


Glioblastoma multiforme (GBM) is the most aggressive primary brain tumour in adults and remains associated with poor patient survival despite advances in treatment @hanif2017. A major challenge in understanding and treating GBM is its substantial molecular heterogeneity. Molecular analyses have identified distinct GBM subtypes characterised by different transcriptional profiles and biological properties, which can influence tumour progression, treatment response, and patient prognosis @verhaak2010. Understanding these molecular differences is therefore important for characterising the biological mechanisms underlying GBM.

Advances in high-throughput transcriptomic technologies have enabled comprehensive characterisation of gene expression patterns in cancer. Transcriptomic data can be used to identify genes whose expression differs between tumour and healthy tissue and to investigate the biological processes associated with these changes @lowe2017. However, lists of differentially expressed genes alone provide limited information about the biological mechanisms underlying the observed changes. Functional enrichment analysis can therefore be used to identify biological processes that are disproportionately represented among differentially expressed genes, providing a biological context for transcriptomic alterations @emmons2023.

Cell death is an important biological process in cancer, and dysregulation of cell death mechanisms can contribute to tumour development and progression @lee2023 @natureeducation2010. Among these mechanisms, apoptosis is a highly regulated form of cell death that plays an important role in maintaining cellular homeostasis and eliminating damaged cells; its intrinsic pathway is closely associated with mitochondrial function, linking apoptosis to mitochondrial processes such as oxidative phosphorylation and the activity of mitochondrial respiratory complexes @lee2023. Disruption of apoptotic signalling can contribute to uncontrolled cell survival.

This thesis investigates transcriptomic alterations in glioblastoma using data from the CPTAC GBM Discovery Study. Differential expression analysis is performed to identify genes whose expression differs between GBM and healthy brain tissue. Gene Ontology enrichment analysis is then used to characterise the biological processes associated with the significant genes, with particular attention given to cell-death-related processes. As apoptosis represents a prominent category among the identified cell-death-related processes, apoptosis-associated genes are subsequently investigated in relation to the mitochondrial respiratory complexes. Protein–protein association network analysis using STRING is used to examine associations between apoptosis-associated proteins and proteins belonging to the mitochondrial respiratory complexes.

The analysis focuses on the Classical molecular subtype of GBM, enabling the relationship between apoptosis and mitochondrial respiratory complexes to be examined within a defined transcriptional context. The aim of this thesis is therefore to characterise transcriptomic alterations in glioblastoma and investigate the transcriptional and network-level associations between apoptosis and mitochondrial respiratory complexes in Classical GBM through differential expression, functional enrichment, and protein–protein association network analysis.

Chapter @background presents the relevant theoretical background, including glioblastoma, its molecular characteristics, apoptosis, mitochondrial function and respiratory complexes, and computational approaches for transcriptomic analysis. Chapter @methodology describes the processing and analysis of the expression data, enrichment of the resulting significant gene set, and integration of cell-death- and mitochondrial respiratory-complex-related genes. Results from the analyses are presented in Chapter @results. An in-depth discussion of the results, limitations, and possible future work is presented in Chapter @discussion.
