#import "../preamble.typ": *

= Introduction <introduction>


Glioblastoma (GBM) is the most aggressive primary brain tumour in adults and remains associated with poor patient survival despite advances in treatment @singh2022. A major challenge in understanding and treating GBM is its substantial molecular heterogeneity. Molecular analyses have identified distinct GBM subtypes characterised by different transcriptional profiles and biological properties, which can influence tumour progression, treatment response, and patient prognosis @verhaak2010. Understanding these molecular differences is therefore important for characterising the biological mechanisms underlying GBM.

Advances in high-throughput transcriptomic technologies have enabled comprehensive characterisation of gene expression patterns in cancer. Transcriptomic data can be used to identify genes whose expression differs between tumour and healthy tissue and to investigate the biological processes associated with these changes @lowe2017. However, lists of differentially expressed genes alone provide limited information about the biological mechanisms underlying the observed changes. Functional enrichment analysis can therefore be used to identify biological processes that are disproportionately represented among differentially expressed genes, providing a biological context for transcriptomic alterations.

Cell death is an important biological process in cancer, and dysregulation of cell death mechanisms can contribute to tumour development and progression @lee2023. Among these mechanisms, apoptosis is a highly regulated form of cell death that plays an important role in maintaining cellular homeostasis and eliminating damaged cells. In cancer, disruption of apoptotic signalling can contribute to uncontrolled cell survival. The intrinsic apoptotic pathway is closely associated with mitochondrial function, linking apoptosis to mitochondrial processes such as oxidative phosphorylation and the activity of mitochondrial respiratory complexes.

This thesis investigates transcriptomic alterations in glioblastoma using data from the CPTAC GBM Discovery Study. Differential expression analysis is performed to identify genes whose expression differs between GBM and healthy brain tissue. Gene Ontology enrichment analysis is then used to characterise the biological processes associated with the significant genes, with particular attention given to cell-death-related processes. As apoptosis represents a prominent category among the identified cell-death-related processes, apoptosis-associated genes are subsequently investigated in relation to the mitochondrial respiratory complexes. Protein–protein interaction network analysis using STRING is used to examine the interactions between apoptosis-associated proteins and proteins belonging to the mitochondrial respiratory complexes.

The aim of this thesis is therefore to characterise transcriptomic alterations in glioblastoma and investigate the relationship between apoptosis and mitochondrial respiratory complexes through functional enrichment and protein–protein interaction network analysis.

Chapter @background presents the relevant knowledge regarding the thesis's topic including glioblastoma and multiomics of glioblastoma. Chapter @methodology shows the processing of expression data, enrichment of the resulting significant gene set, and integration of cell death pathway-related genes. In-depth results and discussion are presented in Chapter @results-discussion.