= Discussion <discussion>

== Transcriptomic alterations and mitochondrial processes in Classical GBM <diff-discuss>

The large proportion of DEGs implies that the transcriptional differences between Classical GBM and normal brain tissue spans across a broad range of biological functions rather than being restricted to a small number of genes. The volcano plot also indicated an asymmetric distribution of log2FC values, with most genes exhibiting moderate changes and a smaller subsets showing a substantially larger fold changes. This further validates the highly heterogeneous profile of GBM as described in Section @gbm-hetero.

To investigate the biological processes associated with these transcriptional alterations, GO enrichment analysis was performed on the significant DEGs. The enrichment results indicate that genes involved in mitochondrial respiratory processes were disproportionately represented among the genes showing significant transcriptional differences in Classical GBM.

The strong representation of mitochondrial respiratory processes is consistent with previous research describing alterations in mitochondrial activities and OXPHOS in GBM. Mitochondrial function has been associated with GBM progression and tumour-cell survival, while differences in oxidative phosphorylation have also been reported between molecular subtypes of GBM @nagy2015 @garofano2021. The present findings therefore agree with previous evidence that mitochondrial metabolic processes are an important component of the molecular characteristics of GBM. However, a more significant enrichment result does not necessarily confirm that the biological processes are more or less active, and must be confirmed via other analyses.

Further inspection of the expression profiles of the individual respiratory complexes showed that genes belonging to Complexes I–V were predominantly down-regulated. This provides further detail in addition to the GO enrichment results, showing that the biological processes represented are accompanied by a generally negative direction of expression change among the genes involved. This may imply reduced mitochondrial activity, potentially leading to improper regulation of cell death-related functions, agreeing with what was proposed in previous literature in Section @mito-apop-connect. 

Additionally, the expression patterns of the apoptosis-associated genes also showed a relatively balanced distribution of upregulated and downregulated genes. This indicates that the transcriptional alterations affecting apoptosis-associated genes were not predominantly directed in a single direction, but instead involved changes in both upregulation and downregulation.

However, these interpretations from the computations remain speculative, as increase or reduction in mitochondrial respiratory and apoptotic activity cannot be determined from transcriptomic data alone @vogel2012, and experimental confirmation is still required.


== Established apoptosis–mitochondrial respiratory relationship in Classical GBM <major-network-discuss>

The relationship between mitochondrial energy metabolism and apoptosis is particularly relevant in GBM, as mitochondrial processes are involved not only in energy production but also in the regulation of apoptotic pathways @nagy2015. Mitochondrial alterations can affect apoptotic signalling, while proteins involved in the respiratory chain may also participate in pathways regulating cell death. In particular, cytochrome c, encoded by CYCS, has a dual role as a component of the mitochondrial electron transport chain and as a central mediator of the intrinsic apoptotic pathway. Under apoptotic conditions, the release of cytochrome c from mitochondria into the cytosol contributes to the formation of the apoptosome and subsequent activation of downstream caspases @jan2019 @kalpage2020.

The identification of CYCS within the relationship between apoptotic genes and mitochondrial respiratory complexes is therefore consistent with this established biological connection. Rather than representing a newly identified mechanism, the result demonstrates that the computational analysis was able to capture a previously established link between mitochondrial respiratory function and apoptosis. More importantly, many previous computational studies of GBM have relied on TCGA-derived transcriptomic data, whereas the present analysis uses the independent CPTAC cohort, showing that this association is also computationally observed in a separate GBM dataset.

Furthermore, the present analysis examines this relationship specifically within Classical GBM, rather than considering GBM as a single molecular group. Thus, while the relationship between mitochondrial respiration, CYCS, and apoptosis itself is well established, its computational observation within Classical GBM using the CPTAC cohort provides a subtype-specific characterization of this relationship. This also provides a basis for investigating whether similar associations are observed in the remaining two major GBM subtypes in future studies.


== Additional network associations between apoptosis and respiratory complexes <minor-network-discuss>


Beyond the established CYCS-mediated connection between mitochondrial respiration and apoptosis, the network analysis identified additional associations between apoptotic genes and the individual mitochondrial respiratory complexes. These findings extend the analysis beyond the canonical relationship and provide a more detailed view of how apoptotic genes may be connected to different components of the mitochondrial respiratory chain in Classical GBM.

The number of associations varied between the respiratory complexes, with Complex I showing the largest number of connections, followed by Complex II, Complex IV, and Complex III, while no associations were identified for Complex V. This variation suggests that the relationship between apoptosis and mitochondrial respiratory complexes may extend beyond the well-established role of CYCS and involve multiple components of the respiratory chain.

The high number of associations identified for Complex I may be related to the multiple established connections between this complex and apoptotic regulation. In addition to its central role in electron transport, Complex I is a major site of mitochondrial ROS production, while several of its subunits have been directly associated with apoptotic processes. For example, NDUFA13/GRIM-19 has been identified as a regulator of cell death, while NDUFS1 can be targeted by caspases during apoptosis @sharma2009 @ricci2004. The relatively high connectivity of Complex I in the present network may therefore reflect the diverse biological links between Complex I and apoptosis-associated processes.

Complex II showed the second-highest number of associations in the network. This finding is consistent with previous evidence describing Complex II as an important mediator of cell-death signalling. Unlike the other respiratory complexes, Complex II also directly links the tricarboxylic acid cycle with the electron transport chain, allowing metabolic changes to influence respiratory and apoptotic signalling. In particular, Complex II has been proposed to function as a general sensor of apoptotic stimuli, with alterations in its activity capable of promoting ROS generation and cell death @grimm2013.

Complex IV showed the third-highest number of associations in the network, with 10 connections. As the terminal complex of the electron transport chain, Complex IV receives electrons from cytochrome c and transfers them to molecular oxygen, completing the electron transfer process @vercellino2022. Its direct interaction with cytochrome c provides an established connection to the apoptotic pathway, as cytochrome c can also function as a mediator of intrinsic apoptosis following its release from mitochondria @huttemann2011. The relatively high number of associations identified for Complex IV may therefore reflect its position at the intersection of mitochondrial respiration and the CYCS-associated apoptotic pathway.

Complex III transfers electrons to cytochrome c, which subsequently transfers electrons to Complex IV as part of the respiratory chain @vercellino2022. Its primarily intermediate role in electron transfer may contribute to its lower connection count compared with the aforementioned two complexes. Furthermore, respiratory activity involving Complex III has been experimentally associated with cytochrome c release during apoptosis @nishimura2001. Although Complex III showed fewer associations than Complexes I and II, these findings indicate that its connection to apoptosis remains relevant within the network.

In contrast, no associations were identified for Complex V. Complex V differs functionally from Complexes I–IV because it does not directly participate in electron transfer or proton pumping; instead, ATP synthase uses the proton-motive force generated by the respiratory chain to produce ATP @vercellino2022. Therefore, it suggests that the network captures interactions that are more direct and not as passive as the Complex V-apoptosis interaction.



It should be emphasized that the studies discussed above do not establish the observed order of connectivity as an absolute biological hierarchy. Rather, they provide possible biological interpretations for the differences in connection counts observed in the present network, while the network itself provides the basis for identifying these associations in Classical GBM.

== Limitations and future work


The findings align closely with previous research results. However, the underlying transcriptomic data used to compare the GBM samples and GTEx controls are not guaranteed to be entirely technically and biologically suitable for a one-to-one comparison, although a justification for the datasets used was presented in Section @data-source. There is also a concern regarding the number of GTEx control samples, which was limited to only 7, as transcriptomic data from the remaining 3 samples were inaccessible. A larger number of control samples could provide greater confidence in the observed differences between the GBM and control groups.

A main concern of the methodology is the trade-off involved in selecting the confidence threshold for the identified STRING interactions. Opting for a higher confidence threshold increases the likelihood that the identified interactions are well-supported, but may eliminate potential interactions that are less well documented. Conversely, using a lower confidence threshold may provide a more comprehensive representation of the system, but can introduce additional noise and make the resulting network less clear. A possible direction for future work would therefore be to compare networks generated using different confidence thresholds and investigate how the identified associations change.

Regarding the networks, the analysis in this thesis was limited to counting the edges representing known associations. While the number of connections provides an overview of the connectivity of each respiratory complex, this metric alone provides limited insight beyond identifying whether associations exist between entities. If the work were to be extended further, additional network metrics in combination with biologically relevant measures could provide greater insight into the structure and organization of the biological systems. For example, measures of centrality or network clustering could be used to identify genes or groups of genes that occupy important positions within the networks.

As discussed in Section @discussion, the analysis in this thesis only covered the Classical GBM subtype. Extending the same analysis to the remaining Proneural and Mesenchymal subtypes, and potentially to other forms of programmed cell death, could provide a broader view of the interactions underlying GBM's proliferative behaviour.

Additionally, as the entities investigated ultimately depend on proteins to carry out their biological functions, integrating proteomic data with the present transcriptomic analysis could provide a more robust interpretation of the results and extend the work into a multi-omics analysis. Such an approach could reveal differences between transcriptomic changes and their corresponding protein products, as gene expression does not necessarily translate directly into protein abundance or function.

As discussed throughout Section @discussion, the computational results obtained in this thesis remain speculative in terms of their functional interpretation and require further experimental confirmation. This is consistent with the nature of bioinformatics research discussed in Section @bioinformatics, where computational findings can provide hypotheses and identify potential biological relationships that subsequently require experimental validation. Overall, the analysis could also be strengthened by incorporating additional statistical analyses to provide further quantitative support for the observed relationships, rather than relying primarily on comparisons with previous literature.
