
#pdf.attach(
  "use-of-ai.typ",
  relationship: "source",
  mime-type: "text/vnd.typst",
  description: "The Typst source code for the front matter section describing how AI was used in producing this work.",
)

I hereby declare, that the AI-based applications used in generating this work are as follows:

#table(
	align: left,
	columns : (70%,30%),
	table.header(
		[*Application*],
		[*Version*]
	),
	[Microsoft 365 Copilot],
	[],
	[Github Copilot],
	[GPT-4.1],
	[ChatGPT],
	[GPT-5.5]
)

== Purpose of the use of AI

Explain here _in detail_, for which purpose and how AI was utilized in writing this thesis.

M365 Copilot was used to suggest papers to read up on background information regarding the thesis's topic, and checking typo and wording throughout the entire work.

Github Copilot and ChatGPT were used mainly for debugging preprocessing code during analysis of multiomics.

== Parts of this work,  where AI was used

List here all chapters, sections, subsections, tables, figures and so forth,
that were generated by an AI, or that an AI had a hand in generating.
